package-lock.json, package.json, src/extensions/entity-manager.extension.ts
#6 easier than expected
Also fixed incorrect type definition for onUpdate
=> entity previous state

cspell.config.yaml, package.json, src/dynamic.ts, src/extensions/entity.extension.ts, src/helpers/device.helper.ts, src/helpers/utility.helper.ts
Part of a pair of PRs, this one will contain the extended description. This is an effort to start creating new patterns within the `dynamic.d.ts` file. 
Currently, the entity state is dumped into a big object, and utility types pick through that to extract helpful unions. This has a major downside of being very heavy on the editor to calculate. More inferring work = slower suggestions and worse editing experience.
This PR sets up the `dynamic.d.ts` to have much more pre calculated data stored in types. It also leverages it with the new `entity.byLabel` / `byArea` etc methods, by directly providing the entity ids associated with each in a new map.
This allows the functions to return exactly the entities that match your request in both type definitions, and implementation
- **design note**: …
=> Improved dynamic types

package.json, src/extensions/entity.extension.ts, src/helpers/utility.helper.ts
1. added event removal function as 3rd param on `onUpdate`
2. added `.byPlatform` (to be given type support in the future)
3. internal types updates
=> Registry updates

package-lock.json, package.json, src/dynamic.ts, src/extensions/entity.extension.ts, src/helpers/fetch/service-list.ts, src/helpers/registry.ts, src/helpers/utility.helper.ts
Adds type support for the `hass.entity.byPlatform` , as well as refining some of the internal utility types. 
Requires matching update to type-writer
=> Platform / integration references for entitites

.github/workflows/check.yml
=> add codecov

package.json
=> add coverage reporter

src/extensions/backup.extension.ts, src/testing/backup.spec.ts
Non-functional / no associated version bump. Adding test coverage
=> Adding unit tests for backup

package-lock.json, package.json, src/dynamic.ts, src/helpers/entity-state.helper.ts
Updating default dynamic types to better support `automation` library
=> Types updates

cspell.config.yaml, package.json, src/extensions/websocket-api.extension.ts, src/helpers/features.helper.ts, src/helpers/index.ts
Big dump of `supported_feature` enums, and some related enums for setting up base home assistant entities. 
Changes is non-functional, but provide type definitions required for future upgrades
=> Supported features and enums

package.json, src/extensions/entity.extension.ts, src/helpers/entity-state.helper.ts
- Adjusting some of the internal types to now be public. No functional changes
=> Exporting callback types

package.json, src/extensions/call-proxy.extension.ts, src/extensions/entity.extension.ts
- Fix to `hass.call` incorrectly emitting errors
- Added traces to usage of `hass.call` prior to init, to better identify offending code
=> Warning fix

package-lock.json, package.json, src/extensions/call-proxy.extension.ts
- Filtered incorrect errors about using `hass.call`, which were a result of internal javascript workflows
=> Filtered incorrect loading error messages

package.json, src/extensions/entity.extension.ts
=> Safer callbacks

src/helpers/notify.helper.ts
Leave it to me to miss the most important part…
- Adding actions to notifications
=> Adding actions to actionable notifications

package.json, src/dynamic.ts, src/extensions/area.extension.ts, src/extensions/entity.extension.ts, src/extensions/fetch-api.extension.ts, src/extensions/id-by.extension.ts, src/extensions/reference.extension.ts, src/helpers/entity-state.helper.ts, src/helpers/fetch/calendar.ts, src/helpers/registry.ts, src/helpers/utility.helper.ts, src/helpers/websocket.helper.ts, src/mock_assistant/extensions/events.extension.ts, src/mock_assistant/extensions/fixtures.extension.ts, src/mock_assistant/helpers/fixtures.ts, src/testing/entity.spec.ts, src/testing/fetch-api.spec.ts, src/testing/ref-by.spec.ts
- Fixed incorrect dev dynamic.d.ts types preventing unions from working as expected
- Spread around usage of `ANY_ENTITY` > `PICK_ENTITY` w/ domain
- Improved some internal type flows
- Added hass.(refBy|idBy).domain
- Added hass.(refBy|idBy).unique_id 
=> Idby domain & unique_id

package.json, src/dynamic.ts, src/extensions/entity.extension.ts, src/extensions/id-by.extension.ts, src/extensions/reference.extension.ts, src/testing/entity.spec.ts
- Adding library side support for `TUniqueId` & the associated mapping
=> Unique id mapping

package-lock.json, package.json, src/e2e/call-proxy.spec.ts, src/e2e/entity.spec.ts, src/e2e/fetch.spec.ts, src/extensions/entity.extension.ts, src/extensions/reference.extension.ts, src/helpers/entity-state.helper.ts, src/testing/entity.spec.ts, src/testing/workflow.spec.ts
=> Add timeout duration to nextState

package.json, src/e2e/area.spec.ts, src/e2e/entity.spec.ts, src/extensions/entity.extension.ts, src/extensions/fetch-api.extension.ts, src/extensions/id-by.extension.ts, src/helpers/id-by.helper.ts, src/helpers/index.ts, src/mock_assistant/main.ts, src/testing/entity.spec.ts
- removed `hass.entity.by*` methods
- updated the `idBy` interface to prevent build issues
=> Build fixing

package.json, src/extensions/reference.extension.ts, src/helpers/entity-state.helper.ts
- add `waitForState`
Will circle back with tests
=> waitForState

cspell.config.yaml, package.json, src/helpers/entity-state.helper.ts, src/helpers/registry.ts, yarn.lock
=> Unit of measurement type defs

src/helpers/notify.helper.ts
=> update actions to be an array

package.json, src/extensions/config.extension.ts, src/extensions/entity.extension.ts
- tweak to allow for numeric unique ids
=> Numeric unique id

package.json, yarn.lock
=> bump package.json

package.json, src/extensions/call-proxy.extension.ts, yarn.lock
return `result.response` from `hass.call` methods that return responses
=> Return response property with hass.call service reponses

src/helpers/notify.helper.ts
actions are optional
Notifications don't require actions.
=> how did I miss that actions should be optional 🤦‍♂️

package.json, src/extensions/call-proxy.extension.ts, src/extensions/entity.extension.ts, src/extensions/websocket-api.extension.ts, yarn.lock
- Adjusted internal boot warnings to not emit traces unless `LOG_LEVEL` === "trace"
=> Add LOG_LEVEL check to boot traces

package.json, yarn.lock
=> Package bumps

package.json, src/helpers/fetch/service-list.mts
Added additional types related to describing service definitions
=> ServiceListSelector

.github/workflows/check.yml, package.json, vitest.config.ts, yarn.lock
- brought back test coverage reporting for codecov 
=> Restore test coverage

.github/workflows/check.yml
Potential fix for [https://github.com/Digital-Alchemy-TS/hass/security/code-scanning/4](https://github.com/Digital-Alchemy-TS/hass/security/code-scanning/4)
To fix the issue, we will add a `permissions` block at the root of the workflow file. This block will specify the minimal permissions required for the workflow to function. Based on the provided steps, the workflow primarily involves checking out the code, setting up Node.js, running build and test commands, and uploading coverage reports to Codecov. The minimal permissions required are:
- `contents: read` for accessing the repository's contents.
- `actions: write` for uploading coverage reports to Codecov.
The `permissions` block will be added at the root level, applying to all jobs in the workflow.
---
_Suggested fixes powered by …
=> Potential fix for code scanning alert no. 4: Workflow does not contain permissions

package.json, src/helpers/constants.mts, src/services/fetch-api.service.mts
=> Update version check to support core dev versions
